import 'babel-polyfill'
import Base from './lottery/base'
import Calculate from './lottery/calculate'
import Interface from './lottery/interface'
import Timer from './lottery/timer'
import $ from 'jquery'
